version: '3.5'
services:
  nginx:
    container_name: nginx
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build:
      context: docker/php7-fpm
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./var/mysql/dbdata/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_DATABASE=mydb"
    ports:
      - "3306:3306"

#  mailcatcher:
#    image: yappabe/mailcatcher
#    ports:
#      - "1025:1025"
#      - "1080:1080"